name: security-action
on:
  push:
    branches: [feature/github-actions]

jobs:
  archive:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Archive Release
      uses: montudor/action-zip@v1
      with:
        args: zip -r -v upload.zip . -i '*.js' '*.html' '*.htm' '*.json' '*.html' '*.ts' '*.tsx' '*.css' '*.jsp' '*.vue'

    - name: salvando artefato
      uses: actions/upload-artifact@v3
      with:
          name: upload.zip
          path: .