name: security-action
on:
  push:
    branches: [feature/container-veracode-action]

jobs:
    
  generate-sandbox-name:
    runs-on: ubuntu-latest
    outputs:
      sandbox-name: ${{ steps.set-sandbox-name.outputs.sandbox-name }}
    steps:
      # Creates the sandbox(logical release descriptive status of current branch)
      - id: set-sandbox-name
        name: set-sandbox-name
        run: |
          echo ${{ github.head_ref }}
          branchName="${{ github.head_ref }}"
          if [[ -z "$branchName" ]]; then
            branchName="${{ github.ref }}"
          fi
          
          if [[ $branchName == *"master"* ]]; then
          echo "::set-output name=sandbox-name::Master"
          elif [[ $branchName == *"main"* ]]; then
          echo "::set-output name=sandbox-name::Main"
          elif [[ $branchName == *"elease/"* ]]; then
          echo "::set-output name=sandbox-name::$branchName"
          elif [[ $branchName == *"feature/"* ]]; then
          echo "::set-output name=sandbox-name::$branchName"
          else
          echo "::set-output name=sandbox-name::Development"
          fi   

  veracode_sast_sandbox_scan:
    runs-on: ubuntu-latest
    needs: [ generate-sandbox-name ]
    container:
      image: veracode/api-wrapper-java:latest
      options: --user root
    steps:
      - name: checkout
        uses: actions/checkout@master
        
      - name: archive and upload branch scan
        run: |
          zip -r -v upload.zip . -i '*.js' '*.html' '*.htm' '*.json' '*.html' '*.ts' '*.tsx' '*.css' '*.jsp' '*.vue'
          java -jar /opt/veracode/api-wrapper.jar -vid "${{ secrets.VERACODE_ID }}" -vkey "${{ secrets.VERACODE_KEY }}" -action UploadAndScan -createprofile true -appname "verademo-javascript-api" -version "${{ github.run_id }}" -filepath upload.zip -teams "Showroom_LucasFerreira" -criticality "Medium" -createsandbox true -sandboxname "${{needs.generate-sandbox-name.outputs.sandbox-name}}" -lifecyclestage "InDevelopmentPreAlpha" 
  
