name: security-action
on:
  push:
    branches: [feature/github-actions]

jobs:
  archive:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Empacotamento dos arquivos
        uses: thedoctor0/zip-release@0.7.5
        with:
          type: 'zip'
          filename: 'upload.zip'
          exclusions: '*.git* *.github* /*node_modules/* *.txt *.png *.jpg *.sample *.yml *.yaml *.zip *.md *.pdf'
          
      - name: Publicando Artefato
        uses: actions/upload-artifact@v2
        with:
          name: pacoteVeracode
          path: upload.zip
          
  veracode_sast_pipeline_scan:
    runs-on: ubuntu-latest
    needs: archive
    name: veracode sast pipeline scan

    steps:
      - name: Download Artefato
        uses: actions/download-artifact@v2
        with:
          name: pacoteVeracode

      - name: pipeline-scan action step
        id: pipeline-scan
        uses: veracode/Veracode-pipeline-scan-action@v1.0.12
        with:
          vid: ${{ secrets.VERACODE_ID }}
          vkey: ${{ secrets.VERACODE_KEY }}
          file: "upload.zip" 