name: security-action
on:
  push:
    branches: [feature/abc1]

jobs:

  veracode_sast_pipeline_scan:
    runs-on: ubuntu-latest
    container:
      image: veracode/pipeline-scan:latest
      options: --user root
    steps:
      - name: checkout
        uses: actions/checkout@master
          
      - name: archive and scan 
        run: |
          zip -r -v upload.zip . -i '*.js' '*.html'
          java -jar /opt/veracode/pipeline-scan.jar -vid "${{ secrets.VERACODE_ID }}" -vkey "${{ secrets.VERACODE_KEY }}" -f upload.zip
    continue-on-error: true
